depth:
  type: None
pose:
  learn_pose: True
  init_pose: True
rendering:
  depth_range: [0.0, 1.0]
  dist_alpha: True
  sample_option: ndc
dataloading:
  path: data/immersive
  scene: ['07_Car_200']
  random_ref: 1
  resize_factor: 4
training:
  out_dir:  out/immersive/07_Car_200
  vis_resolution: [48, 64]
extract_images:
  resolution: [480, 640]